### ISSUE TITLE
Task: Landing page of Employers (HTML and CSS) needs to be done (Front-End).

### ISSUE THREAD

**Issue by amczuboka** [Holyvert/2Squared-soen341project2023#10]
#7

**Comment by Holyvert** [comment]
The same landing page for all users.
including this issue #13

**Comment by Holyvert** [comment]
do the nav and footer.
remove the unnecessary info

**Comment by Holyvert** [comment]
3 U.S. points

**Comment by amczuboka** [comment]
HTML is almost done (90%), but since authentication is not done, the page is not able to switch from student to employer so we move this task to sprint 3

**Comment by amczuboka** [comment]
Can close since authentication was finished by Guillaume and Oliver
