### ISSUE TITLE
Task: Creation of job form page of Employers (HTML and CSS) needs to be done (Front-End). This page is where the Employer creates a post.

### ISSUE THREAD

**Issue by amczuboka** [Holyvert/2Squared-soen341project2023#11]
#7

**Comment by Holyvert** [comment]
Here is what the for should have


Name of Organization 
Job Title:
Job Location:
Job Location Type:
Salary (specify $/hour or $/year):
Duration:
Name of Supervisor:
Job Description:

**Comment by Holyvert** [comment]
make all of them obligatory fields

**Comment by Holyvert** [comment]
we assume the employer already has a company name associated with their profile

**Comment by KarinaSandur** [comment]
Done! Just needs approval to merge into Sprint2!
