### ISSUE TITLE
Wiki page

### ISSUE THREAD

**Issue by Guillaume-Lachapelle** [Holyvert/2Squared-soen341project2023#2]
Create a Wiki page documenting meeting minutes and notes, and remove Word document from project files.

**Comment by Holyvert** [comment]
> Create a Wiki page documenting meeting minutes and notes, and remove Word document from project files.
yep

**Comment by MillerSty** [comment]
Set up wiki page. Document still needs to be removed

**Comment by KarinaSandur** [comment]
I created a new branch off of Sprint1 called Sprint1_with_deletedWordDoc and I have created a pull request to merge the latter with the former. I have added all participants as reviewers to this pull request.

**Comment by Holyvert** [comment]
looks good
