### ISSUE TITLE
As a student, I would like to apply to job-posts 

### ISSUE THREAD

**Issue by amczuboka** [Holyvert/2Squared-soen341project2023#41]
Linked to user story #7

**Comment by IsabelleCzuboka** [comment]
Task Breakdown: 
1. (Backend) When apply button is clicked, add student to database for that specific posting. #50 
2. (HTML) Add in student landing page a tab "Applied to"(or smt like that) and create that page #56
3. Backend) When clicking on the tab applied to as a student, it will show all the job posting that student has applied to. #57

**Comment by IsabelleCzuboka** [comment]
All issues related to user story are closed so this can be closed as well
