### ISSUE TITLE
Add "Candidates" page (Front-End).

### ISSUE THREAD

**Issue by amczuboka** [Holyvert/2Squared-soen341project2023#49]
#42

**Comment by amczuboka** [comment]
If no one has applied to post, then "edit" button will appear. 
If at least one person has applied to post, the "See Candidates" button will appear.

**Comment by IsabelleCzuboka** [comment]
Add a template of how students will be shown in job posting, with the name, program and cv along with a checkmark that can be clicked if employer wants to select for interview. Also we need a button at the end "selectForInterview" that will notify the specific students chosen.

**Comment by KarinaSandur** [comment]
An employer must visit 'My Postings' and click on a particular post in order to be able to see a button labelled 'See Candidates' which will redirect them to the candidates page.

**Comment by amczuboka** [comment]
Task has been merged into sprint 3
