### ISSUE TITLE
User Story: As a user, I would like to login in to my own account either as a student, an employer or an admin in order to access personalized information 

### ISSUE THREAD

**Issue by IsabelleCzuboka** [Holyvert/2Squared-soen341project2023#5]
#4 
This user story is about setting up the login page visually. There is also the backend aspect concerning cookies. As well, it is about bringing a user to their specific account whether admin, student or company which will all have slightly different UI specifics.

**Comment by amczuboka** [comment]
Task Break Down:

1. For Students, when I log in, on the landing page, I should be able to access my profile (HTML and CSS) Front-End.
2. For Students, the profile page should be done (HTML and CSS) Front-End. 
3. For Students, the profile information should be saved to the student-profiles database when the user saves their info (Back-End).

**Comment by IsabelleCzuboka** [comment]
Task related to this user story, #53, has been completed!
