### ISSUE TITLE
(HTML) Add in student landing page a tab "Applied to"(or smt like that) and create that page

### ISSUE THREAD

**Issue by IsabelleCzuboka** [Holyvert/2Squared-soen341project2023#56]
#41 
So when a student logs into their account, they need to see a tab where they can click to view all the jobs they have applied to. Therefore, that tab needs to be created in the landing page. This tasks is also about creating the page that will be showing all the postings they have applied to. Do not overcomplicate this page, it will basically use the function like the landing page to generate the job postings in card format, therefore in this task you do not need to recreate a format to demonstrate the applied job. Mostly just the background.

**Comment by amczuboka** [comment]
Has been merged into Sprint 3
