### ISSUE TITLE
User Story: As a student, I would like to browse through the job postings to view all of the available jobs.

### ISSUE THREAD

**Issue by IsabelleCzuboka** [Holyvert/2Squared-soen341project2023#6]
#4 
This user story is linked to creating the page related to viewing the list of available job positions, as well as each individual job posting page. Concerning back end, when a company goes to create a posting, setting up an immediate page for this posting and adding it to the available list of posting for student are certain necessary tasks to complete.

**Comment by amczuboka** [comment]
**Task Break Down:**

1. Landing page for Students (html and css) needs to be done (Front-End). This page contains all the available job postings. 
2. Individual job-post page for Students (html and css) needs to be done (Front-End).
3. Landing page of Employers (html and css) needs to be done (Front-End).
4. Creation of job-post page of Employers (html and css) needs to be done (Front-End). This page is where the Employer creates a post. 
5. Creation of job-posts database in Firebase (Back-End).
6. Add post to job-posts database in Firebase after Employer creates a new post (Back-End).
7. Render all job-posts from Firebase to the landing page of students from the job-posts database (Back-End).
