### ISSUE TITLE
User Story: As an employer, I want to upload job postings so that students can view and apply to them.

### ISSUE THREAD

**Issue by IsabelleCzuboka** [Holyvert/2Squared-soen341project2023#7]
#4 
This user story is linked to creating the page related to creating a job posting. This is the page the company sees when it wants to add a posting. There will be certain backend task related to this as well.

**Comment by amczuboka** [comment]
**Task Break Down:**

1. Landing page of Employers (html and css) needs to be done (Front-End).
2. Creation of job-post page of Employers (html and css) needs to be done (Front-End). This page is where the Employer creates a post.

**Comment by amczuboka** [comment]
Tasks has been completed for this user story and has been merged into sprint 3
