### ISSUE TITLE
User Story: As an admin, I want to be able to oversee all user profiles and job postings (ex: add or modify job postings).

### ISSUE THREAD

**Issue by KarinaSandur** [Holyvert/2Squared-soen341project2023#8]
This user story relates to the creation of a user interface for admins (which is different from that of a student or employer). Certain backend tasks will need to be completed to provide admins the authority to manage user profiles and job postings.

**Comment by amczuboka** [comment]
#4

**Comment by Guillaume-Lachapelle** [comment]
No admin needed, but all users and postings can be modified in firebase
