### ISSUE TITLE
Discuss the final presentation and assign tasks if needed for its completion 

### ISSUE THREAD

**Issue by IsabelleCzuboka** [Holyvert/2Squared-soen341project2023#98]
We need to start thinking and assigning work to complete the oral presentation at the end of the semester. Ideally, we would structure the presentation in this meeting so that all can work individually on equal sized parts.

**Comment by amczuboka** [comment]
Guidelines: Relate course goal objectives with project. Talk about the process of working with agile methodology SCRUM. Check  "Course Learning Outcomes" in Course Outline Word Document.

**Comment by IsabelleCzuboka** [comment]
We divided the task of the oral presentation, and discussed its content
